on: [push]

jobs:
  yaml2env_job:
    runs-on: ubuntu-latest
    name: A job to read env from yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read env
        uses: ./
        with:
          file: './test.yaml'
          key-path: "['my-app','containers','env']"
        
      - name: Print env
        run: |
          echo ENV: ${{ env.ENV }}
          echo ENDPOINT: ${{ env.ENDPOINT }}